org: testingdynamo

service: sdcs

provider:
  name: aws
  runtime: python3.12
  region: ${env:AWS_REGION, 'us-east-2'}
  stage: ${opt:stage, 'develop'}
  httpApi:
    cors:
      allowedOrigins:
        - '*'
      allowedHeaders:
        - Content-Type
        - X-Amz-Date
        - Authorization
        - X-Api-Key
        - X-Amz-Security-Token
        - X-Amz-User-Agent
      allowedMethods:
        - OPTIONS
        - GET
        - POST
  environment:
    DATABASE_NAME: ${env:DATABASE_NAME}
    API_KEY: ${env:API_KEY}

    COMPRESSOR_AMPS_TABLE_NAME: ${env:COMPRESSOR_AMPS_TABLE_NAME}
    COND_FAN_AMPS_TABLE_NAME: ${env:COND_FAN_AMPS_TABLE_NAME}
    LIQUID_LINE_PRESSURE_TABLE_NAME: ${env:LIQUID_LINE_PRESSURE_TABLE_NAME}
    LIQUID_LINE_TEMPERATURE_TABLE_NAME: ${env:LIQUID_LINE_TEMPERATURE_TABLE_NAME}
    LOG_DATA_TABLE_NAME: ${env:LOG_DATA_TABLE_NAME}
    RETURN_AIR_CO2_TABLE_NAME: ${env:RETURN_AIR_CO2_TABLE_NAME}
    RETURN_AIR_HUMIDITY_TABLE_NAME: ${env:RETURN_AIR_HUMIDITY_TABLE_NAME}
    RETURN_AIR_TEMPERATURE_TABLE_NAME: ${env:RETURN_AIR_TEMPERATURE_TABLE_NAME}
    SPACE_CO2_TABLE_NAME: ${env:SPACE_CO2_TABLE_NAME}
    SPACE_HUMIDITY_TABLE_NAME: ${env:SPACE_HUMIDITY_TABLE_NAME}
    SPACE_TEMPERATURE_TABLE_NAME: ${env:SPACE_TEMPERATURE_TABLE_NAME}
    SUCTION_LINE_TEMPERATURE_TABLE_NAME: ${env:SUCTION_LINE_TEMPERATURE_TABLE_NAME}
    SUCTION_LINE_PRESSURE_TABLE_NAME: ${env:SUCTION_LINE_PRESSURE_TABLE_NAME}
    SUPPLY_AIR_CO2_TABLE_NAME: ${env:SUPPLY_AIR_CO2_TABLE_NAME}
    SUPPLY_AIR_FAN_AMPS_TABLE_NAME: ${env:SUPPLY_AIR_FAN_AMPS_TABLE_NAME}
    SUPPLY_AIR_HUMIDITY_TABLE_NAME: ${env:SUPPLY_AIR_HUMIDITY_TABLE_NAME}
    SUPPLY_AIR_TEMPERATURE_TABLE_NAME: ${env:SUPPLY_AIR_TEMPERATURE_TABLE_NAME}
    VIBRATION_SENSOR_TABLE_NAME: ${env:VIBRATION_SENSOR_TABLE_NAME}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - timestream:WriteRecords
        - timestream:Select
        - timestream:DescribeEndpoints
        - timestream:DescribeTable
        - timestream:ListTables
      Resource:
        - "arn:aws:timestream:${self:provider.region}:*:database/${env:DATABASE_NAME}/table/${env:COMPRESSOR_AMPS_TABLE_NAME}"
        - "arn:aws:timestream:${self:provider.region}:*:database/${env:DATABASE_NAME}/table/${env:COND_FAN_AMPS_TABLE_NAME}"
        - "arn:aws:timestream:${self:provider.region}:*:database/${env:DATABASE_NAME}/table/${env:LIQUID_LINE_PRESSURE_TABLE_NAME}"
        - "arn:aws:timestream:${self:provider.region}:*:database/${env:DATABASE_NAME}/table/${env:LIQUID_LINE_TEMPERATURE_TABLE_NAME}"
        - "arn:aws:timestream:${self:provider.region}:*:database/${env:DATABASE_NAME}/table/${env:LOG_DATA_TABLE_NAME}"
        - "arn:aws:timestream:${self:provider.region}:*:database/${env:DATABASE_NAME}/table/${env:RETURN_AIR_CO2_TABLE_NAME}"
        - "arn:aws:timestream:${self:provider.region}:*:database/${env:DATABASE_NAME}/table/${env:RETURN_AIR_HUMIDITY_TABLE_NAME}"
        - "arn:aws:timestream:${self:provider.region}:*:database/${env:DATABASE_NAME}/table/${env:RETURN_AIR_TEMPERATURE_TABLE_NAME}"
        - "arn:aws:timestream:${self:provider.region}:*:database/${env:DATABASE_NAME}/table/${env:SPACE_CO2_TABLE_NAME}"
        - "arn:aws:timestream:${self:provider.region}:*:database/${env:DATABASE_NAME}/table/${env:SPACE_HUMIDITY_TABLE_NAME}"
        - "arn:aws:timestream:${self:provider.region}:*:database/${env:DATABASE_NAME}/table/${env:SPACE_TEMPERATURE_TABLE_NAME}"
        - "arn:aws:timestream:${self:provider.region}:*:database/${env:DATABASE_NAME}/table/${env:SUCTION_LINE_TEMPERATURE_TABLE_NAME}"
        - "arn:aws:timestream:${self:provider.region}:*:database/${env:DATABASE_NAME}/table/${env:SUCTION_LINE_PRESSURE_TABLE_NAME}"
        - "arn:aws:timestream:${self:provider.region}:*:database/${env:DATABASE_NAME}/table/${env:SUPPLY_AIR_CO2_TABLE_NAME}"
        - "arn:aws:timestream:${self:provider.region}:*:database/${env:DATABASE_NAME}/table/${env:SUPPLY_AIR_FAN_AMPS_TABLE_NAME}"
        - "arn:aws:timestream:${self:provider.region}:*:database/${env:DATABASE_NAME}/table/${env:SUPPLY_AIR_HUMIDITY_TABLE_NAME}"
        - "arn:aws:timestream:${self:provider.region}:*:database/${env:DATABASE_NAME}/table/${env:SUPPLY_AIR_TEMPERATURE_TABLE_NAME}"
        - "arn:aws:timestream:${self:provider.region}:*:database/${env:DATABASE_NAME}/table/${env:VIBRATION_SENSOR_TABLE_NAME}"
        - "arn:aws:timestream:${self:provider.region}:*:database/${env:DATABASE_NAME}"
        - "*"

functions:
  ############################################COMPRESSOR_AMPS###########################################################
  store_compressor_amps_data:
    handler: handler_store_data.store_compressor_amps
    events:
      - httpApi:
          path: /sdcs/compressor_amps/data
          method: POST

  get_compressor_amps_data:
    handler: handler_get_data.get_compressor_amps
    events:
      - httpApi:
          path: /sdcs/compressor_amps/data
          method: GET


  ############################################COND_FAN_AMPS#############################################################
  store_cond_fan_amps_data:
    handler: handler_store_data.store_cond_fan_amps
    events:
      - httpApi:
          path: /sdcs/cond_fan_amps/data
          method: POST

  get_cond_fan_amps_data:
    handler: handler_get_data.get_cond_fan_amps
    events:
      - httpApi:
          path: /sdcs/cond_fan_amps/data
          method: GET


  ############################################LIQUID_LINE_PRESSURE######################################################
  store_liquid_line_pressure_data:
    handler: handler_store_data.store_liquid_line_pressure
    events:
      - httpApi:
          path: /sdcs/liquid_line_pressure/data
          method: POST

  get_liquid_line_pressure_data:
    handler: handler_get_data.get_liquid_line_pressure
    events:
      - httpApi:
          path: /sdcs/liquid_line_pressure/data
          method: GET


  ############################################LIQUID_LINE_TEMPERATURE###################################################
  store_liquid_line_temperature_data:
    handler: handler_store_data.store_liquid_line_temperature
    events:
      - httpApi:
          path: /sdcs/liquid_line_temperature/data
          method: POST

  get_liquid_line_temperature_data:
    handler: handler_get_data.get_liquid_line_temperature
    events:
      - httpApi:
          path: /sdcs/liquid_line_temperature/data
          method: GET


  ############################################LOG_DATA##################################################################
  get_logging_data:
    handler: handler_get_data.get_log_data
    events:
      - httpApi:
          path: /sdcs/log_data/data
          method: GET


  ############################################RETURN_AIR_CO2##########################################################
  store_return_air_co2_data:
    handler: handler_store_data.store_return_air_co2
    events:
      - httpApi:
          path: /sdcs/return_air_co2/data
          method: POST

  get_return_air_co2_data:
    handler: handler_get_data.get_return_air_co2
    events:
      - httpApi:
          path: /sdcs/return_air_co2/data
          method: GET


  ############################################RETURN_AIR_HUMIDITY######################################################
  store_return_air_humidity_data:
    handler: handler_store_data.store_return_air_humidity
    events:
      - httpApi:
          path: /sdcs/return_air_humidity/data
          method: POST

  get_return_air_humidity_data:
    handler: handler_get_data.get_return_air_humidity
    events:
      - httpApi:
          path: /sdcs/return_air_humidity/data
          method: GET


  ############################################RETURN_AIR_TEMPERATURE##################################################
  store_return_air_temperature_data:
    handler: handler_store_data.store_return_air_temperature
    events:
      - httpApi:
          path: /sdcs/return_air_temperature/data
          method: POST

  get_return_air_temperature_data:
    handler: handler_get_data.get_return_air_temperature
    events:
      - httpApi:
          path: /sdcs/return_air_temperature/data
          method: GET


  ############################################SPACE_CO2###############################################################
  store_space_co2_data:
    handler: handler_store_data.store_space_co2
    events:
      - httpApi:
          path: /sdcs/space_co2/data
          method: POST

  get_space_co2_data:
    handler: handler_get_data.get_space_co2
    events:
      - httpApi:
          path: /sdcs/space_co2/data
          method: GET

  ############################################SPACE_HUMIDITY##########################################################
  store_space_humidity_data:
    handler: handler_store_data.store_space_humidity
    events:
      - httpApi:
          path: /sdcs/space_humidity/data
          method: POST

  get_space_humidity_data:
    handler: handler_get_data.get_space_humidity
    events:
      - httpApi:
          path: /sdcs/space_humidity/data
          method: GET


  ############################################SPACE_TEMPERATURE#######################################################
  store_space_temperature_data:
    handler: handler_store_data.store_space_temperature
    events:
      - httpApi:
          path: /sdcs/space_temperature/data
          method: POST

  get_space_temperature_data:
    handler: handler_get_data.get_space_temperature
    events:
      - httpApi:
          path: /sdcs/space_temperature/data
          method: GET


  ############################################SUCTION_LINE_PRESSURE####################################################
  store_suction_line_pressure_data:
    handler: handler_store_data.store_suction_line_pressure
    events:
      - httpApi:
          path: /sdcs/suction_line_pressure/data
          method: POST

  get_suction_line_pressure_data:
    handler: handler_get_data.get_suction_line_pressure
    events:
      - httpApi:
          path: /sdcs/suction_line_pressure/data
          method: GET


  ############################################SUCTION_LINE_TEMPERATURE#################################################
  store_suction_line_temperature_data:
    handler: handler_store_data.store_suction_line_temperature
    events:
      - httpApi:
          path: /sdcs/suction_line_temperature/data
          method: POST

  get_suction_line_temperature_data:
    handler: handler_get_data.get_suction_line_temperature
    events:
      - httpApi:
          path: /sdcs/suction_line_temperature/data
          method: GET


  ############################################SUPPLY_AIR_CO2###########################################################
  store_supply_air_co2_data:
    handler: handler_store_data.store_supply_air_co2
    events:
      - httpApi:
          path: /sdcs/supply_air_co2/data
          method: POST

  get_supply_air_co2_data:
    handler: handlers.supply_air_co2.get_supply_air_co2
    events:
      - httpApi:
          path: /sdcs/supply_air_co2/data
          method: GET


  ############################################SUPPLY_AIR_FAN_AMPS######################################################
  store_supply_air_fan_amps_data:
    handler: handler_store_data.store_supply_air_fan_amps
    events:
      - httpApi:
          path: /sdcs/supply_air_fan_amps/data
          method: POST

  get_supply_air_fan_amps_data:
    handler: handler_get_data.get_supply_air_fan_amps
    events:
      - httpApi:
          path: /sdcs/supply_air_fan_amps/data
          method: GET


  ############################################SUPPLY_AIR_HUMIDITY####################################################
  store_supply_air_humidity_data:
    handler: handler_store_data.store_supply_air_humidity
    events:
      - httpApi:
          path: /sdcs/supply_air_humidity/data
          method: POST

  get_supply_air_humidity_data:
    handler: handler_get_data.get_supply_air_humidity
    events:
      - httpApi:
          path: /sdcs/supply_air_humidity/data
          method: GET


  ############################################SUPPLY_AIR_TEMPERATURE#################################################
  store_supply_air_temperature_data:
    handler: handler_store_data.store_supply_air_temperature
    events:
      - httpApi:
          path: /sdcs/supply_air_temperature/data
          method: POST

  get_supply_air_temperature_data:
    handler: handler_get_data.get_supply_air_temperature
    events:
      - httpApi:
          path: /sdcs/supply_air_temperature/data
          method: GET


  ############################################VIBRATION_SENSOR########################################################
  store_vibration_sensor_data:
    handler: handler_store_data.store_vibration_sensor
    events:
      - httpApi:
          path: /sdcs/vibration_sensor/data
          method: POST

  get_vibration_sensor_data:
    handler: handler_get_data.get_vibration_sensor
    events:
      - httpApi:
          path: /sdcs/vibration_sensor/data
          method: GET



plugins:
  - serverless-python-requirements
  - serverless-dotenv-plugin

custom:

  pythonRequirements:
    dockerizePip: non-linux